---
name: 🚀 Spécifier une évolution
description: Renseigner les informations nécessaires pour créer ou améliorer une fonctionnalité pour cartes.gouv.fr
labels: ["enhancement"]
projects: ["IGNF/52"]
type: "Feature"
body:
  - type: textarea
    id: context
    attributes:
      label: 📣 1. Contexte produit
      description: |
        Décrivez le parcours de base de la fonctionnalité et la tâche générique que l'utilisateur cherche à accomplir, indépendamment de l'outil.
      placeholder: |
        exemple : |
        ### Parcours concerné |
        Éditeur -> Barre de gestion -> Enregistrer |
        Éditeur -> Barre d'étape -> Enregistrer |
        ### Situation d'usage (JTBD) |
        L'agent souhaite enregistrer la carte qu'il est en train de créer pour pouvoir l'utiliser ou la modifier plus tard.
  - type: textarea
    id: user-story
    attributes:
      label: 🎯 2. User Story
      description: |
        Décrivez précisément le comportement de la nouvelle fonctionnalité.
      placeholder: |
        - En tant que [type d'utilisateur / persona] |
        - Je veux [action concrète à réaliser] |
        - Afin de [valeur attendue / bénéfice] |
    validations:
      required: true
  - type: textarea
    id: parcours-recette
    attributes:
      label: ✅ 3. Parcours utilisateur et critères d'acceptation (ce qu'il faut vérifier lors de la recette fonctionnelle)
      description: |
        Décrivez tous les éléments fonctionnels que l'outil doit apporter pour considérer le ticket comme terminé.
      placeholder: |
        - [ ] L'utilisateur clique sur "Enregistrer" : une modale s'ouvre |
        - [ ] L'utilisateur saisit un nom (obligatoire), une thématique (obligatoire) et une description (optionnelle) |
        - ... |
        - [ ] L'enregistrement est immédiat |
        - [ ] L'utilisateur comprend grâce à l'interface si sa carte a bien été enregistrée
    validations:
      required: true
  - type: textarea
    id: design
    attributes:
      label: 🎨 4. Design
      description: |
        Décrivez les éléments de design nécéssaire au développement de la fonctionnalité.
      placeholder: |
        - Composition |
        - Comportement |
        - Contenus |
        - Emplacement |
        - Points de rupture |
        - Raccourcis clavier |
        - Lien Figma
  - type: textarea
    id: solution-technique
    attributes:
      label: ⚙️ 5. Solution proposée et contraintes techniques
      description: |
        Décrivez ici la solution technique proposée pour répondre au fonctionnel et/ou les contraintes techniques à prendre en compte
  - type: textarea
    id: impact-attendu
    attributes:
      label: 📊 6. impact attendu
      description: |
        Décrivez quelle valeur cela apporte-t-il à l'utilisateur, et comment le mesurer.
      placeholder: |
        - Valeur utilisateur : [Exemple : Faciliter la décision => l'agent gagne du temps et fiabilise ses analyses] |
        - Mesure : [Exemple : % d'imports réussis sans erreur, temps moyen de traitement gagné]
  - type: textarea
    id: liens
    attributes:
      label: 🔗 7. Liens et informations supplémentaires
      description: |
        Renseignez les liens utiles à l'évolution ou toute autre information utile ne pouvant pas être renseignée dans une autre catégorie.
      placeholder: |
        - Données de test : [lien] |
        - Documentation annexe : [lien]
  - type: textarea
    id: historique
    attributes:
      label: 🎥 8. Historique et décisions produit
      description: |
        Partie à remplir avant la clôture du ticket. Renseignez ici la synthèse des décisions et informations importantes concernant l'évolution du ticket
