/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { DeletedResponse, MapResearch, MapView } from "../model";

import {
  getDeleteMapByEditIdResponseMock,
  getGetMapByViewIdResponseMock,
  getGetMapEditByEditIdResponseMock,
  getGetMapsResponseMock,
  getGetMapsUsersResponseMock,
  getPatchMapByEditIdResponseMock,
  getPostMapResponseMock,
} from "./map.faker";

export {
  getGetMapsResponseMock,
  getPostMapResponseMock,
  getGetMapsUsersResponseMock,
  getGetMapByViewIdResponseMock,
  getGetMapEditByEditIdResponseMock,
  getDeleteMapByEditIdResponseMock,
  getPatchMapByEditIdResponseMock,
} from "./map.faker";

export const getGetMapsMockHandler = (
  overrideResponse?:
    | MapResearch
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<MapResearch> | MapResearch),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/maps",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetMapsResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPostMapMockHandler = (
  overrideResponse?:
    | MapView
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<MapView> | MapView),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/maps",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPostMapResponseMock(),
        { status: 201 },
      );
    },
    options,
  );
};

export const getGetMapsUsersMockHandler = (
  overrideResponse?:
    | string[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<string[]> | string[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/maps/users",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetMapsUsersResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetMapByViewIdMockHandler = (
  overrideResponse?:
    | MapView
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<MapView> | MapView),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/maps/:viewId",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetMapByViewIdResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetMapEditByEditIdMockHandler = (
  overrideResponse?:
    | MapView
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<MapView> | MapView),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/maps/:editId/edit",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getGetMapEditByEditIdResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetMapFileByViewIdMockHandler = (
  overrideResponse?:
    | unknown
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<unknown> | unknown),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/maps/:viewId/file",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getGetMapFileByEditIdMockHandler = (
  overrideResponse?:
    | unknown
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<unknown> | unknown),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/api/maps/:editId/edit/file",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};

export const getDeleteMapByEditIdMockHandler = (
  overrideResponse?:
    | DeletedResponse
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<DeletedResponse> | DeletedResponse),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    "*/api/maps/:editId",
    async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getDeleteMapByEditIdResponseMock(),
        { status: 204 },
      );
    },
    options,
  );
};

export const getPatchMapByEditIdMockHandler = (
  overrideResponse?:
    | MapView
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) => Promise<MapView> | MapView),
  options?: RequestHandlerOptions,
) => {
  return http.patch(
    "*/api/maps/:editId",
    async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPatchMapByEditIdResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getPostMapFileByEditIdMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/api/maps/:editId/file",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};
export const getMapMock = () => [
  getGetMapsMockHandler(),
  getPostMapMockHandler(),
  getGetMapsUsersMockHandler(),
  getGetMapByViewIdMockHandler(),
  getGetMapEditByEditIdMockHandler(),
  getGetMapFileByViewIdMockHandler(),
  getGetMapFileByEditIdMockHandler(),
  getDeleteMapByEditIdMockHandler(),
  getPatchMapByEditIdMockHandler(),
  getPostMapFileByEditIdMockHandler(),
];
