/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import { apiURL } from "../../env";

import type {
  BadRequestResponse,
  DeletedResponse,
  ForbiddenResponse,
  GetMapsParams,
  GetMapsUsersParams,
  InvalidResponse,
  MapResearch,
  MapView,
  NotConnectedResponse,
  NotFoundResponse,
  PatchMapByEditIdBody,
  PostMapBody,
  PostMapFileByEditIdBody,
} from "../model";

export type getMapsResponse200 = {
  data: MapResearch;
  status: 200;
};

export type getMapsResponse206 = {
  data: MapResearch;
  status: 206;
};

export type getMapsResponse401 = {
  data: NotConnectedResponse;
  status: 401;
};

export type getMapsResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type getMapsResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getMapsResponseSuccess = (
  getMapsResponse200 | getMapsResponse206
) & {
  headers: Headers;
};
export type getMapsResponseError = (
  getMapsResponse401 | getMapsResponse403 | getMapsResponse404
) & {
  headers: Headers;
};

export type getMapsResponse = getMapsResponseSuccess | getMapsResponseError;

export const getGetMapsUrl = (params?: GetMapsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `${apiURL}/api/maps?${stringifiedParams}`
    : `${apiURL}/api/maps`;
};

export const getMaps = async (
  params?: GetMapsParams,
  options?: RequestInit,
): Promise<getMapsResponse> => {
  const res = await fetch(getGetMapsUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMapsResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getMapsResponse;
};

export type postMapResponse201 = {
  data: MapView;
  status: 201;
};

export type postMapResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type postMapResponse401 = {
  data: NotConnectedResponse;
  status: 401;
};

export type postMapResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type postMapResponseSuccess = postMapResponse201 & {
  headers: Headers;
};
export type postMapResponseError = (
  postMapResponse400 | postMapResponse401 | postMapResponse404
) & {
  headers: Headers;
};

export type postMapResponse = postMapResponseSuccess | postMapResponseError;

export const getPostMapUrl = () => {
  return `${apiURL}/api/maps`;
};

export const postMap = async (
  postMapBody: PostMapBody,
  options?: RequestInit,
): Promise<postMapResponse> => {
  const formData = new FormData();
  formData.append(`carte`, JSON.stringify(postMapBody.carte));
  formData.append(`file`, postMapBody.file);

  const res = await fetch(getPostMapUrl(), {
    ...options,
    method: "POST",
    body: formData,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postMapResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as postMapResponse;
};

export type getMapsUsersResponse200 = {
  data: string[];
  status: 200;
};

export type getMapsUsersResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getMapsUsersResponseSuccess = getMapsUsersResponse200 & {
  headers: Headers;
};
export type getMapsUsersResponseError = getMapsUsersResponse404 & {
  headers: Headers;
};

export type getMapsUsersResponse =
  getMapsUsersResponseSuccess | getMapsUsersResponseError;

export const getGetMapsUsersUrl = (params?: GetMapsUsersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `${apiURL}/api/maps/users?${stringifiedParams}`
    : `${apiURL}/api/maps/users`;
};

/**
 * Autocompletion des utilisateurs ayant des cartes publiques correspondant aux critères de recherche
 */
export const getMapsUsers = async (
  params?: GetMapsUsersParams,
  options?: RequestInit,
): Promise<getMapsUsersResponse> => {
  const res = await fetch(getGetMapsUsersUrl(params), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMapsUsersResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMapsUsersResponse;
};

export type getMapByViewIdResponse200 = {
  data: MapView;
  status: 200;
};

export type getMapByViewIdResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getMapByViewIdResponse451 = {
  data: InvalidResponse;
  status: 451;
};

export type getMapByViewIdResponseSuccess = getMapByViewIdResponse200 & {
  headers: Headers;
};
export type getMapByViewIdResponseError = (
  getMapByViewIdResponse404 | getMapByViewIdResponse451
) & {
  headers: Headers;
};

export type getMapByViewIdResponse =
  getMapByViewIdResponseSuccess | getMapByViewIdResponseError;

export const getGetMapByViewIdUrl = (viewId: number | string) => {
  return `${apiURL}/api/maps/${viewId}`;
};

/**
 * Récupérer les metadata de la carte par son identifiant de visualisation
 */
export const getMapByViewId = async (
  viewId: number | string,
  options?: RequestInit,
): Promise<getMapByViewIdResponse> => {
  const res = await fetch(getGetMapByViewIdUrl(viewId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMapByViewIdResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMapByViewIdResponse;
};

export type getMapEditByEditIdResponse200 = {
  data: MapView;
  status: 200;
};

export type getMapEditByEditIdResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getMapEditByEditIdResponse451 = {
  data: InvalidResponse;
  status: 451;
};

export type getMapEditByEditIdResponseSuccess =
  getMapEditByEditIdResponse200 & {
    headers: Headers;
  };
export type getMapEditByEditIdResponseError = (
  getMapEditByEditIdResponse404 | getMapEditByEditIdResponse451
) & {
  headers: Headers;
};

export type getMapEditByEditIdResponse =
  getMapEditByEditIdResponseSuccess | getMapEditByEditIdResponseError;

export const getGetMapEditByEditIdUrl = (editId: number | string) => {
  return `${apiURL}/api/maps/${editId}/edit`;
};

/**
 * Récupérer les metadata de la carte par son identifiant d'édition
 */
export const getMapEditByEditId = async (
  editId: number | string,
  options?: RequestInit,
): Promise<getMapEditByEditIdResponse> => {
  const res = await fetch(getGetMapEditByEditIdUrl(editId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMapEditByEditIdResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMapEditByEditIdResponse;
};

export type getMapFileByViewIdResponse200 = {
  data: unknown;
  status: 200;
};

export type getMapFileByViewIdResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getMapFileByViewIdResponse451 = {
  data: InvalidResponse;
  status: 451;
};

export type getMapFileByViewIdResponseSuccess =
  getMapFileByViewIdResponse200 & {
    headers: Headers;
  };
export type getMapFileByViewIdResponseError = (
  getMapFileByViewIdResponse404 | getMapFileByViewIdResponse451
) & {
  headers: Headers;
};

export type getMapFileByViewIdResponse =
  getMapFileByViewIdResponseSuccess | getMapFileByViewIdResponseError;

export const getGetMapFileByViewIdUrl = (viewId: number | string) => {
  return `${apiURL}/api/maps/${viewId}/file`;
};

/**
 * Récupérer les data de la carte par son identifiant de visualisation
 */
export const getMapFileByViewId = async (
  viewId: number | string,
  options?: RequestInit,
): Promise<getMapFileByViewIdResponse> => {
  const res = await fetch(getGetMapFileByViewIdUrl(viewId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMapFileByViewIdResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMapFileByViewIdResponse;
};

export type getMapFileByEditIdResponse200 = {
  data: unknown;
  status: 200;
};

export type getMapFileByEditIdResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getMapFileByEditIdResponse451 = {
  data: InvalidResponse;
  status: 451;
};

export type getMapFileByEditIdResponseSuccess =
  getMapFileByEditIdResponse200 & {
    headers: Headers;
  };
export type getMapFileByEditIdResponseError = (
  getMapFileByEditIdResponse404 | getMapFileByEditIdResponse451
) & {
  headers: Headers;
};

export type getMapFileByEditIdResponse =
  getMapFileByEditIdResponseSuccess | getMapFileByEditIdResponseError;

export const getGetMapFileByEditIdUrl = (editId: number | string) => {
  return `${apiURL}/api/maps/${editId}/edit/file`;
};

/**
 * Récupérer les data de la carte par son identifiant d'édition
 */
export const getMapFileByEditId = async (
  editId: number | string,
  options?: RequestInit,
): Promise<getMapFileByEditIdResponse> => {
  const res = await fetch(getGetMapFileByEditIdUrl(editId), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMapFileByEditIdResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMapFileByEditIdResponse;
};

export type deleteMapByEditIdResponse204 = {
  data: DeletedResponse;
  status: 204;
};

export type deleteMapByEditIdResponse401 = {
  data: NotConnectedResponse;
  status: 401;
};

export type deleteMapByEditIdResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type deleteMapByEditIdResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type deleteMapByEditIdResponseSuccess = deleteMapByEditIdResponse204 & {
  headers: Headers;
};
export type deleteMapByEditIdResponseError = (
  | deleteMapByEditIdResponse401
  | deleteMapByEditIdResponse403
  | deleteMapByEditIdResponse404
) & {
  headers: Headers;
};

export type deleteMapByEditIdResponse =
  deleteMapByEditIdResponseSuccess | deleteMapByEditIdResponseError;

export const getDeleteMapByEditIdUrl = (editId: number | string) => {
  return `${apiURL}/api/maps/${editId}`;
};

export const deleteMapByEditId = async (
  editId: number | string,
  options?: RequestInit,
): Promise<deleteMapByEditIdResponse> => {
  const res = await fetch(getDeleteMapByEditIdUrl(editId), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteMapByEditIdResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deleteMapByEditIdResponse;
};

export type patchMapByEditIdResponse200 = {
  data: MapView;
  status: 200;
};

export type patchMapByEditIdResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type patchMapByEditIdResponse401 = {
  data: NotConnectedResponse;
  status: 401;
};

export type patchMapByEditIdResponse403 = {
  data: ForbiddenResponse;
  status: 403;
};

export type patchMapByEditIdResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type patchMapByEditIdResponseSuccess = patchMapByEditIdResponse200 & {
  headers: Headers;
};
export type patchMapByEditIdResponseError = (
  | patchMapByEditIdResponse400
  | patchMapByEditIdResponse401
  | patchMapByEditIdResponse403
  | patchMapByEditIdResponse404
) & {
  headers: Headers;
};

export type patchMapByEditIdResponse =
  patchMapByEditIdResponseSuccess | patchMapByEditIdResponseError;

export const getPatchMapByEditIdUrl = (editId: number | string) => {
  return `${apiURL}/api/maps/${editId}`;
};

export const patchMapByEditId = async (
  editId: number | string,
  patchMapByEditIdBody: PatchMapByEditIdBody,
  options?: RequestInit,
): Promise<patchMapByEditIdResponse> => {
  const getHeaders = (
    h?: NonNullable<RequestInit["headers"]>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<
      string | readonly string[] | undefined
    >(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  const res = await fetch(getPatchMapByEditIdUrl(editId), {
    ...options,
    method: "PATCH",
    headers: {
      "Content-Type": "application/json",
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(patchMapByEditIdBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchMapByEditIdResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as patchMapByEditIdResponse;
};

export type postMapFileByEditIdResponse200 = {
  data: void;
  status: 200;
};

export type postMapFileByEditIdResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type postMapFileByEditIdResponseSuccess =
  postMapFileByEditIdResponse200 & {
    headers: Headers;
  };
export type postMapFileByEditIdResponseError =
  postMapFileByEditIdResponse404 & {
    headers: Headers;
  };

export type postMapFileByEditIdResponse =
  postMapFileByEditIdResponseSuccess | postMapFileByEditIdResponseError;

export const getPostMapFileByEditIdUrl = (editId: number | string) => {
  return `${apiURL}/api/maps/${editId}/file`;
};

export const postMapFileByEditId = async (
  editId: number | string,
  postMapFileByEditIdBody: PostMapFileByEditIdBody,
  options?: RequestInit,
): Promise<postMapFileByEditIdResponse> => {
  const formData = new FormData();
  formData.append(`file`, postMapFileByEditIdBody.file);

  const res = await fetch(getPostMapFileByEditIdUrl(editId), {
    ...options,
    method: "POST",
    body: formData,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postMapFileByEditIdResponse["data"] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postMapFileByEditIdResponse;
};
