/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import type { DeletedResponse, MapResearch, MapView } from "../model";

export const getGetMapsResponseMock = (
  overrideResponse: Partial<Extract<MapResearch, object>> = {},
): MapResearch =>
  faker.helpers.arrayElement([
    {
      maps: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        type: faker.string.alpha({ length: { min: 10, max: 20 } }),
        title: faker.string.alpha({ length: { min: 10, max: 20 } }),
        description: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          null,
        ]),
        updated_at: faker.date.past().toISOString().slice(0, 19) + "Z",
        nb_view: faker.number.int(),
        img_url: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          null,
        ]),
        organization_id: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          null,
        ]),
        organization_name: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          null,
        ]),
        user: faker.string.alpha({ length: { min: 10, max: 20 } }),
        user_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
        theme: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          null,
        ]),
        theme_id: faker.helpers.arrayElement([faker.number.int(), null]),
        share: faker.string.alpha({ length: { min: 10, max: 20 } }),
        premium: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          null,
        ]),
        valid: faker.datatype.boolean(),
        active: faker.datatype.boolean(),
        title_url: faker.string.alpha({ length: { min: 10, max: 20 } }),
        view_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
        view_url: faker.internet.url(),
        bbox: Array.from(
          { length: faker.number.int({ min: 4, max: 4 }) },
          (_, i) => i + 1,
        ).map(() => faker.number.float({ fractionDigits: 2 })),
        edit_id: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          null,
        ]),
        edit_url: faker.helpers.arrayElement([faker.internet.url(), null]),
      })),
      themes: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        theme: faker.string.alpha({ length: { min: 10, max: 20 } }),
        count: faker.number.int(),
      })),
      organizations: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        organization: faker.string.alpha({ length: { min: 10, max: 20 } }),
        public_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
        count: faker.number.int(),
      })),
      users: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        user: faker.string.alpha({ length: { min: 10, max: 20 } }),
        count: faker.number.int(),
      })),
      types: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        type: faker.string.alpha({ length: { min: 10, max: 20 } }),
        count: faker.number.int(),
      })),
      premiums: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        premium: faker.string.alpha({ length: { min: 10, max: 20 } }),
        count: faker.number.int(),
      })),
      actives: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        active: faker.datatype.boolean(),
        count: faker.number.int(),
      })),
      valides: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        valid: faker.datatype.boolean(),
        count: faker.number.int(),
      })),
      shares: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        share: faker.string.alpha({ length: { min: 10, max: 20 } }),
        count: faker.number.int(),
      })),
      query: faker.string.alpha({ length: { min: 10, max: 20 } }),
      count: faker.number.int(),
      limit: faker.helpers.arrayElement([faker.number.int(), null]),
      offset: faker.number.int(),
      ...overrideResponse,
    },
    {
      maps: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        type: faker.string.alpha({ length: { min: 10, max: 20 } }),
        title: faker.string.alpha({ length: { min: 10, max: 20 } }),
        description: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          null,
        ]),
        updated_at: faker.date.past().toISOString().slice(0, 19) + "Z",
        nb_view: faker.number.int(),
        img_url: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          null,
        ]),
        organization_id: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          null,
        ]),
        organization_name: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          null,
        ]),
        user: faker.string.alpha({ length: { min: 10, max: 20 } }),
        user_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
        theme: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          null,
        ]),
        theme_id: faker.helpers.arrayElement([faker.number.int(), null]),
        share: faker.string.alpha({ length: { min: 10, max: 20 } }),
        premium: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          null,
        ]),
        valid: faker.datatype.boolean(),
        active: faker.datatype.boolean(),
        title_url: faker.string.alpha({ length: { min: 10, max: 20 } }),
        view_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
        view_url: faker.internet.url(),
        bbox: Array.from(
          { length: faker.number.int({ min: 4, max: 4 }) },
          (_, i) => i + 1,
        ).map(() => faker.number.float({ fractionDigits: 2 })),
        edit_id: faker.helpers.arrayElement([
          faker.string.alpha({ length: { min: 10, max: 20 } }),
          null,
        ]),
        edit_url: faker.helpers.arrayElement([faker.internet.url(), null]),
      })),
      themes: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        theme: faker.string.alpha({ length: { min: 10, max: 20 } }),
        count: faker.number.int(),
      })),
      organizations: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        organization: faker.string.alpha({ length: { min: 10, max: 20 } }),
        public_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
        count: faker.number.int(),
      })),
      users: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        user: faker.string.alpha({ length: { min: 10, max: 20 } }),
        count: faker.number.int(),
      })),
      types: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        type: faker.string.alpha({ length: { min: 10, max: 20 } }),
        count: faker.number.int(),
      })),
      premiums: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        premium: faker.string.alpha({ length: { min: 10, max: 20 } }),
        count: faker.number.int(),
      })),
      actives: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        active: faker.datatype.boolean(),
        count: faker.number.int(),
      })),
      valides: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        valid: faker.datatype.boolean(),
        count: faker.number.int(),
      })),
      shares: Array.from(
        { length: faker.number.int({ min: 1, max: 10 }) },
        (_, i) => i + 1,
      ).map(() => ({
        share: faker.string.alpha({ length: { min: 10, max: 20 } }),
        count: faker.number.int(),
      })),
      query: faker.string.alpha({ length: { min: 10, max: 20 } }),
      count: faker.number.int(),
      limit: faker.helpers.arrayElement([faker.number.int(), null]),
      offset: faker.number.int(),
      ...overrideResponse,
    },
  ]);

export const getPostMapResponseMock = (): MapView => ({
  ...{
    title: faker.string.alpha({ length: { min: 10, max: 20 } }),
    title_url: faker.string.alpha({ length: { min: 10, max: 20 } }),
    description: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    theme: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    theme_id: faker.helpers.arrayElement([faker.number.int(), null]),
    organization: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    organization_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    organization_name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    type: faker.string.alpha({ length: { min: 10, max: 20 } }),
    premium: faker.string.alpha({ length: { min: 10, max: 20 } }),
    active: faker.datatype.boolean(),
    valid: faker.datatype.boolean(),
    created_at: faker.date.past().toISOString().slice(0, 19) + "Z",
    updated_at: faker.date.past().toISOString().slice(0, 19) + "Z",
    nb_view: faker.number.int(),
    img_url: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    share: faker.string.alpha({ length: { min: 10, max: 20 } }),
    bbox: Array.from(
      { length: faker.number.int({ min: 4, max: 4 }) },
      (_, i) => i + 1,
    ).map(() => faker.number.float({ fractionDigits: 2 })),
    view_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    view_url: faker.internet.url(),
    edit_id: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    user: faker.string.alpha({ length: { min: 10, max: 20 } }),
    user_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    author: faker.string.alpha({ length: { min: 10, max: 20 } }),
    author_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
  },
  ...{
    data_url: faker.internet.url(),
    data_edit_url: faker.helpers.arrayElement([faker.internet.url(), null]),
    editor: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
  },
});

export const getGetMapsUsersResponseMock = (): string[] =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, () =>
    faker.word.sample(),
  );

export const getGetMapByViewIdResponseMock = (): MapView => ({
  ...{
    title: faker.string.alpha({ length: { min: 10, max: 20 } }),
    title_url: faker.string.alpha({ length: { min: 10, max: 20 } }),
    description: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    theme: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    theme_id: faker.helpers.arrayElement([faker.number.int(), null]),
    organization: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    organization_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    organization_name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    type: faker.string.alpha({ length: { min: 10, max: 20 } }),
    premium: faker.string.alpha({ length: { min: 10, max: 20 } }),
    active: faker.datatype.boolean(),
    valid: faker.datatype.boolean(),
    created_at: faker.date.past().toISOString().slice(0, 19) + "Z",
    updated_at: faker.date.past().toISOString().slice(0, 19) + "Z",
    nb_view: faker.number.int(),
    img_url: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    share: faker.string.alpha({ length: { min: 10, max: 20 } }),
    bbox: Array.from(
      { length: faker.number.int({ min: 4, max: 4 }) },
      (_, i) => i + 1,
    ).map(() => faker.number.float({ fractionDigits: 2 })),
    view_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    view_url: faker.internet.url(),
    edit_id: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    user: faker.string.alpha({ length: { min: 10, max: 20 } }),
    user_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    author: faker.string.alpha({ length: { min: 10, max: 20 } }),
    author_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
  },
  ...{
    data_url: faker.internet.url(),
    data_edit_url: faker.helpers.arrayElement([faker.internet.url(), null]),
    editor: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
  },
});

export const getGetMapEditByEditIdResponseMock = (): MapView => ({
  ...{
    title: faker.string.alpha({ length: { min: 10, max: 20 } }),
    title_url: faker.string.alpha({ length: { min: 10, max: 20 } }),
    description: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    theme: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    theme_id: faker.helpers.arrayElement([faker.number.int(), null]),
    organization: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    organization_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    organization_name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    type: faker.string.alpha({ length: { min: 10, max: 20 } }),
    premium: faker.string.alpha({ length: { min: 10, max: 20 } }),
    active: faker.datatype.boolean(),
    valid: faker.datatype.boolean(),
    created_at: faker.date.past().toISOString().slice(0, 19) + "Z",
    updated_at: faker.date.past().toISOString().slice(0, 19) + "Z",
    nb_view: faker.number.int(),
    img_url: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    share: faker.string.alpha({ length: { min: 10, max: 20 } }),
    bbox: Array.from(
      { length: faker.number.int({ min: 4, max: 4 }) },
      (_, i) => i + 1,
    ).map(() => faker.number.float({ fractionDigits: 2 })),
    view_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    view_url: faker.internet.url(),
    edit_id: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    user: faker.string.alpha({ length: { min: 10, max: 20 } }),
    user_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    author: faker.string.alpha({ length: { min: 10, max: 20 } }),
    author_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
  },
  ...{
    data_url: faker.internet.url(),
    data_edit_url: faker.helpers.arrayElement([faker.internet.url(), null]),
    editor: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
  },
});

export const getDeleteMapByEditIdResponseMock = (
  overrideResponse: Partial<Extract<DeletedResponse, object>> = {},
): DeletedResponse => ({
  code: faker.helpers.arrayElement([faker.number.int(), undefined]),
  message: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getPatchMapByEditIdResponseMock = (): MapView => ({
  ...{
    title: faker.string.alpha({ length: { min: 10, max: 20 } }),
    title_url: faker.string.alpha({ length: { min: 10, max: 20 } }),
    description: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    theme: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    theme_id: faker.helpers.arrayElement([faker.number.int(), null]),
    organization: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    organization_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    organization_name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    type: faker.string.alpha({ length: { min: 10, max: 20 } }),
    premium: faker.string.alpha({ length: { min: 10, max: 20 } }),
    active: faker.datatype.boolean(),
    valid: faker.datatype.boolean(),
    created_at: faker.date.past().toISOString().slice(0, 19) + "Z",
    updated_at: faker.date.past().toISOString().slice(0, 19) + "Z",
    nb_view: faker.number.int(),
    img_url: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    share: faker.string.alpha({ length: { min: 10, max: 20 } }),
    bbox: Array.from(
      { length: faker.number.int({ min: 4, max: 4 }) },
      (_, i) => i + 1,
    ).map(() => faker.number.float({ fractionDigits: 2 })),
    view_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    view_url: faker.internet.url(),
    edit_id: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
    user: faker.string.alpha({ length: { min: 10, max: 20 } }),
    user_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
    author: faker.string.alpha({ length: { min: 10, max: 20 } }),
    author_id: faker.string.alpha({ length: { min: 10, max: 20 } }),
  },
  ...{
    data_url: faker.internet.url(),
    data_edit_url: faker.helpers.arrayElement([faker.internet.url(), null]),
    editor: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      null,
    ]),
  },
});
