/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */

/**
 * Emprise visible de la carte (haut, droite, bas, gauche)
 * @minItems 4
 * @maxItems 4
 */
export type Bbox = number[];
