/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import type { Bbox } from "./bbox";

/**
 * Objet carte à envoyer lors d'ajout / modification d'une carte
 */
export interface MapAdd {
  /** Titre de la carte */
  title: string;
  /**
   * Description de la carte
   * @nullable
   */
  description?: string | null;
  /** identifiant du theme */
  theme_id: number;
  /** Type de la carte ('macarte', 'mesadresses', statistic', storymap') */
  type: string;
  /** Premium de la carte ('default', 'edugeo') */
  premium: string;
  /** Identifiant public de l'organisation. */
  organization_id?: string;
  /** Carte active (par ex : terminée ou non) */
  active: boolean;
  /**
   * Publication de la carte ('atlas', 'public', 'private').
   * Si 'organization' est rempli, la valeur sera 'private' sauf si l'utilisateur connecté est owner
   */
  share?: string;
  bbox: Bbox;
  /**
   * Url de l'image illustrant la carte. Peut être une chaîne vide.
   * @nullable
   */
  img_url?: string | null;
  /** Identifiant public du créateur (si la carte est dans une organisation) */
  creator_id?: string;
}
