/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */

export type MapResearchTypesItem = {
  /** Nom du type */
  type: string;
  /** Nombre de cartes */
  count: number;
};
