/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */

/**
 * Agrégat du nombre de cartes par thème dans les résultats de recherche
 */
export interface MapResearchTheme {
  /** Nom du thème, ou 'undefined' pour les cartes sans thème */
  theme: string;
  /** Nombre de cartes */
  count: number;
}
