/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import type { Bbox } from "./bbox";

/**
 * Carte renvoyée dans les résultats de recherche. Cet objet est construit depuis une requête SQL, et non directement depuis le normalizer d'entité Map.
 */
export interface MapResearchItem {
  /** Type de la carte ('macarte', 'storymap') */
  type: string;
  /** Titre de la carte */
  title: string;
  /**
   * Description de la carte
   * @nullable
   */
  description: string | null;
  /** Dernière date de mise à jour de la carte */
  updated_at: string;
  /** Nombre total de vues */
  nb_view: number;
  /**
   * URL de l'image illustrant la carte. Peut être une chaîne vide.
   * @nullable
   */
  img_url: string | null;
  /**
   * Identifiant public de l'organisation
   * @nullable
   */
  organization_id: string | null;
  /**
   * Nom de l'organisation
   * @nullable
   */
  organization_name: string | null;
  /** Nom public de l'auteur de la carte */
  user: string;
  /** Identifiant public de l'auteur de la carte */
  user_id: string;
  /**
   * Thème lié à la carte
   * @nullable
   */
  theme: string | null;
  /**
   * Id du thème
   * @nullable
   */
  theme_id: number | null;
  /** Publication de la carte ('atlas', 'public', 'private') */
  share: string;
  /**
   * Premium de la carte ('default', 'edugeo')
   * @nullable
   */
  premium: string | null;
  /** Carte valide */
  valid: boolean;
  /** Carte active */
  active: boolean;
  /** Titre de la carte, adapté pour être utilisé dans les URLs */
  title_url: string;
  /** Id utilisé pour la visualisation */
  view_id: string;
  /** Lien vers la visualisation de la carte */
  view_url: string;
  bbox: Bbox;
  /**
   * Id utilisé pour l'édition, renvoyé uniquement en contexte profile
   * @nullable
   */
  edit_id?: string | null;
  /**
   * Lien vers l'édition de la carte, renvoyé uniquement en contexte profile
   * @nullable
   */
  edit_url?: string | null;
}
