/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */

export type MapResearchValidesItem = {
  /** booléen indiquant valide/invalide */
  valid: boolean;
  /** Nombre de cartes */
  count: number;
};
