/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */

export type MapResearchActivesItem = {
  /** booléen indiquant active/inactive */
  active: boolean;
  /** Nombre de cartes */
  count: number;
};
