/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */

export type MapResearchUsersItem = {
  /** Nom public de l'utilisateur */
  user: string;
  /** Nombre de cartes */
  count: number;
};
