/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import type { MapResearchActivesItem } from "./mapResearchActivesItem";
import type { MapResearchItem } from "./mapResearchItem";
import type { MapResearchOrganization } from "./mapResearchOrganization";
import type { MapResearchPremiumsItem } from "./mapResearchPremiumsItem";
import type { MapResearchSharesItem } from "./mapResearchSharesItem";
import type { MapResearchTheme } from "./mapResearchTheme";
import type { MapResearchTypesItem } from "./mapResearchTypesItem";
import type { MapResearchUsersItem } from "./mapResearchUsersItem";
import type { MapResearchValidesItem } from "./mapResearchValidesItem";

/**
 * Recherche des cartes
 */
export interface MapResearch {
  maps: MapResearchItem[];
  themes: MapResearchTheme[];
  organizations: MapResearchOrganization[];
  users: MapResearchUsersItem[];
  types: MapResearchTypesItem[];
  premiums: MapResearchPremiumsItem[];
  actives: MapResearchActivesItem[];
  valides: MapResearchValidesItem[];
  shares: MapResearchSharesItem[];
  /** Mot(s) contenu(s) dans le titre, la description ou le theme des cartes */
  query: string;
  /** Nombre de cartes correspondant à la recherche */
  count: number;
  /**
   * Nombre de cartes reçues dans la requête. Peut être null lorsque toutes les cartes sont demandées.
   * @nullable
   */
  limit: number | null;
  /** Nombre de cartes à passer avant de les inclure dans la requete */
  offset: number;
}
