/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */

/**
 * Le nombre d'objets à ignorer avant de commencer à collecter l'ensemble de résultats
 */
export type OffsetParameter = number;
