/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import type { MapAdd } from "./mapAdd";

export type PatchMapByEditIdBody = MapAdd & {
  /** Demande à modifier l'id de modification */
  new_edit_id?: boolean;
};
