/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import type { MapAdd } from "./mapAdd";

export type PostMapBody = {
  carte: MapAdd;
  /** Contenu de la carte au format .carte */
  file: Blob | File;
};
